// JsFromRoutes CacheKey 373ae80c2861e90dbc4b342c00749048
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as devisePasswords } from '~/api/Devise/PasswordsApi'
export { default as usersSessions } from '~/api/Users/SessionsApi'
export { default as usersRegistrations } from '~/api/Users/RegistrationsApi'
export { default as tasks } from '~/api/TasksApi'
export { default as schedules } from '~/api/SchedulesApi'
