// JsFromRoutes CacheKey a981f12e619b08d7992e1655eb3a04c8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  list: definePathHelper('get', '/schedules'),
  get: definePathHelper('get', '/schedules/:id'),
}
