// JsFromRoutes CacheKey 1f1ea9ee20a4aa1d1145e6e969a0d80f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/schedules'),
  get: definePathHelper('get', '/schedules/:id'),
}
