// JsFromRoutes CacheKey 119788936481a4f43be6b3f3984c31c3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/tasks'),
  create: definePathHelper('post', '/tasks'),
  update: definePathHelper('patch', '/tasks/:id'),
}
