// JsFromRoutes CacheKey 0b7d4dc2911524655e802382edbe39e0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  new: definePathHelper('get', '/register'),
  create: definePathHelper('post', '/register'),
}
