// JsFromRoutes CacheKey bc3b2baa542bafae04d100e3bec10c17
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/login'),
  create: definePathHelper('post', '/login'),
}
