// JsFromRoutes CacheKey 3a3582bf83667fa7e2f3276ea7ffded9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  new: definePathHelper('get', '/login'),
  create: definePathHelper('post', '/login'),
  destroy: definePathHelper('delete', '/logout'),
}
